stages:
  - build
  - py_test

build:
  stage: build
  script:
  - ./run_tests.sh
  only:
  - master

py_test:
  stage: py_test
  script:
  - pip install -r requirements.txt
  - ./generate_input.py 50 20 20 10 test
  - ./generate_input.py clean
  only:
  - master
